config/routes.rb
Rails.application.routes.draw do
  get '/pets', to: 'pets#index', as: :pets
  post '/pets', to: 'pets#create'
  get '/pets/new', to: 'pets#new', as: :new_pet
  get '/pets/:id', to: 'pets#show', as: :pet
  get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch '/pets/:id', to: 'pets#update'
  delete '/pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  # associations
  # validations
  validates :found_on, presence: true
  validates :address, presence: true
  SPECIES = ['horse', 'lion', 'capybara', 'dog', 'eagle']
  validates :species, inclusion: { in: SPECIES }
  enum status: [:healthy, :injured, :dead]

  def found_days_ago
    (Date.today - found_on).to_i
  end
end

# Pet::SPECIES

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new.html.erb'
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      # render 'edit.html.erb'
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :found_on, :species, :status)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindMyPet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_card.html.erb
<div class="card-product">
  <%= image_tag "http://source.unsplash.com/featured/?#{pet.species}&#{rand(1000)}"%>
  <div class="card-product-infos">
    <h2><%= pet.name %></h2>
    <p><%= pet.address %></p>
    <p>Health: <%= pet.status %></p>
    <p>Found <%= pluralize(pet.found_days_ago, 'day') %> ago</p>
  </div>
  <%= link_to '', pet_path(pet), class: 'card-link' %>
</div>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :found_on, html5: true %>
  <%= f.input :species, collection: Pet::SPECIES, include_blank: false %>
  <%= f.input :status, collection: Pet.statuses.keys, include_blank: false %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <h1>Update <%= @pet.name %></h1>
  <%= render 'pets/form' %>
</div>

app/views/pets/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Found Pets</h1>
    <%= link_to new_pet_path do %>
      <i class="fas fa-plus-square btn-light"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @pets.each do |pet| %>
      <%= render 'pets/card', pet: pet %>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container">
  <h1>Add Found Pet</h1>
  <%= render 'pets/form' %>
</div>

app/views/pets/show.html.erb
<div class="container mt-5">
  <p><%= link_to '< Back', pets_path, class: 'btn-light' %></p>
  <div class="card-product">
    <%= image_tag "http://source.unsplash.com/featured/?#{@pet.species}&#{rand(1000)}"%>
    <div class="card-product-infos">
      <h2><%= @pet.name %></h2>
      <p><%= @pet.address %></p>
      <p>Found <%= pluralize(@pet.found_days_ago, 'day') %> ago</p>
    </div>
    <div class="d-flex">
      <%= link_to edit_pet_path(@pet), class: 'btn-light', class: 'card-action card-destroy' do %>
        <i class="fas fa-pencil-alt"></i>
      <% end %>
      <%= link_to pet_path(@pet), method: :delete, data: { confirm: "you sure?" }, class: 'card-action card-edit' do %>
        <i class="fas fa-times"></i>
      <% end %>
    </div>
  </div>
</div>